name: Build and Deploy OSM Report

on:
  pull_request:
    branches:
      - main
  schedule:
    # Run at midnight (00:00) UTC every day
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write # Needed to post comments
  # Add actions read permission to list artifacts
  actions: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install

      - name: Run all tests
        run: npm test

  build-report:
    needs: run-tests
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: ${{ (github.event_name == 'pull_request' || github.event_name == 'push') && 'simplified' || 'full' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install 

      - name: Generate Reports and Build Production CSS
        run: |
          node src/main.js
          npm run build:css

      - name: Check Build Type
        run: echo "The build type is $BUILD_TYPE"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        if: env.BUILD_TYPE == 'full'
        id: deployment
        uses: actions/deploy-pages@v4

  comment-on-pr:
    # Only run this job for pull_request events
    if: github.event_name == 'pull_request'
    needs: build-report
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the Artifact ID from the workflow run (NO CHANGE NEEDED HERE)
      - name: Get Artifact ID
        id: get_artifact
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });

            // The artifact uploaded by 'actions/upload-pages-artifact@v3' is usually named 'github-pages'
            const pagesArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === 'github-pages'
            );
            
            if (pagesArtifact) {
              // Set the artifact ID as an output for the next step
              core.setOutput('artifact_id', pagesArtifact.id);
            } else {
              core.setFailed("Could not find the 'github-pages' artifact.");
            }
          
      # Step 2: Create the direct download link and post the comment
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ **Build Complete!**
            
            The simplified page build has been created. You can **download the zipped artifact** directly here:
            
            **[Download github-pages.zip](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.get_artifact.outputs.artifact_id }})**
            
            *Note: You must be logged into GitHub to download this file.*